rvm:
  - 1.9.3
  - 2.0.0
notifications:
  email:
    recipients:
       - jon.phenow@sportngin.com
    on_success: change
    on_failure: always
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libxmlsec1-dev
